### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by Sandip75** [codeb1ooded/codeb1ooded.github.io#1]
When I was scrolling the page down that time I saw than navigation bar is taking too much of space and for reader page is scrolled again and again.

**Comment by codeb1ooded** [comment]
@Sandip75 Can you add screenshots or GIFs, if possible, to elaborate?

Also, the repository is now maintained in PHP for which the code is present at https://github.com/codeb1ooded/codeb1ooded.github.io/tree/master/codeblooded

And the live link of project is
http://codeb1ooded.com
